### ISSUE TITLE
Tiddler Import breaks tags with spaces

### ISSUE THREAD

**Issue by Takiro** [lucasbordeau/obsidian-tiddlywiki#15]
TiddlyWiki allows Tags to have spaces but Obsidian does not. Would be nice to have an additional option in the importer to tell it how to handle spaces like *replace spaces in tags with underscore if possible* or something. To prevent tags and links from breaking.

**Comment by lucasbordeau** [comment]
@Takiro I'm just pushing a PR which refactors a lot of the code, should be easier to work with now. 

Would you be willing to try this ? I think it's really easy.

**Comment by Takiro** [comment]
Just tried it looks good. Images are now imported properly too. Really nice work!

Only thing basically missing from the whole import are filters and lists but when I look at how different they're compared to Obsidians I don't think there's really a chance to get those translated into Obsidians (or dataviews) syntax automagically.
