### ISSUE TITLE
Converting TiddlyWiki Transclusions when importing Tiddlers

### ISSUE THREAD

**Issue by Takiro** [lucasbordeau/obsidian-tiddlywiki#16]
TiddlyWiki has a feature called *transclusion* which is basically the same as embedding a note into another note in Obsidian.

Tiddly's transclusion syntax is `{{Name of another Tiddler}}` which translates to Obsidian's embedding  `![[Name of another Tiddler]]`. 

Fortunately pretty similar.

**Comment by lucasbordeau** [comment]
@Takiro Published a new release, you might want to test

**Comment by Takiro** [comment]
Works perfectly as far as I can tell :+1:

**Comment by Takiro** [comment]
I just noticed one quirk regarding transclusion/embedding of images. Tiddly allows to give images additional properties, for example to render them at lower width or height. This looks like this in TiddlyWiki `[img width=500 [honey_touch__sketch.jpg]]` while Obsidian does it like [this](https://help.obsidian.md/Linking+notes+and+files/Embed+files#Embed+an+image+in+a+note) `![[honey_touch__sketch.jpg|100]]`. 
Currently the importer doesn't recognizes the different syntax and leaves it as is.
