### ISSUE TITLE
Interesting in hearing more about what this does

### ISSUE THREAD

**Issue by anthrolisp** [lucasbordeau/obsidian-tiddlywiki#6]
I am interested in exporting a folder of markdown files (currently edited in Obsidian) into a TiddlyWiki that I could host on the web, or share with colleagues. Could this plugin help? Thanks!

**Comment by lucasbordeau** [comment]
This plugin only exports your markdown folder to a TiddlyWiki json file.

For the hosting part you'll have to look through the documentation of TiddlyWiki, you have existing solutions like TiddlyWiki Node server and expose it.

**Comment by anthrolisp** [comment]
Both exporting and importing from Obsidian to TiddlyWiki works for me!
