### ISSUE TITLE
Two feature requests/questions (directory level export and embedded images)

### ISSUE THREAD

**Issue by anthrolisp** [lucasbordeau/obsidian-tiddlywiki#7]
Just tested. This is awesome!

Is it possible to only export from Obsidian a selected directory?
And also include export of embedded images?

Thank you in advance!!

**Comment by lucasbordeau** [comment]
Thank you for your feedback.

The image feature is on my roadmap.

I'll add the folder selection feature too.

**Comment by anthrolisp** [comment]
Being able to export specific folders from Obsidian would be incredible. Thank you!

**Comment by lucasbordeau** [comment]
I've created #11 and #10 to answer your feedback.

**Comment by anthrolisp** [comment]
This is incredible!!
